name: redditum_flapp
description: App for Redditum Web

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  logger: ^1.1.0
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^6.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: DroidSans
      fonts:
        - asset: fonts/DroidSans.ttf
        - asset: fonts/DroidSans-Bold.ttf

flutter_icons:
  image_path: "assets/images/logo-white-icon.png"
  remove_alpha_ios: true
  ios: true
  android: "launcher_icon"

flutter_intl:
  enabled: true
  main_locale: es